id: I1187C7C4
source: null
source_file: null
initial_creation_type: input
imported: '2022-07-04T10:08:18.607644'
last_modified: '2022-07-04T10:08:18.607662'
parser: null
source_metadata:
  base:
    7E92:
      base_file: 7E92.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
